name: technology_wall
description: "Technology Wall, a leading IT company based in Riyadh, KSA.
  Offering integrated, smart, and digitized solutions."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  another_flushbar: ^1.12.30
  cloud_firestore: ^4.13.5
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  emailjs: ^1.3.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.5

  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.1.2
  flutter_improved_scrolling: ^0.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^6.1.0
  html: ^0.15.4
  intl: ^0.18.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.2
  webview_flutter_platform_interface: ^2.8.0
  webview_flutter_web: ^0.2.2+3

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/logo.png"
    adaptive_background_color: "#FFFFF"
    adaptive_icon_background_color: "#FFFFF"
    background_color: #fffff
      null
    theme_color: "#f7f7f7"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lang/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
